### PR TITLE
add toplevel __init__.py

### PR DESCRIPTION
**Pull request by timotheecour**
* seems like it should be there according to https://medium.com/@ramrajchandradevan/python-init-py-modular-imports-81b746e58aae and https://stackoverflow.com/questions/44911789/why-do-i-need-init-py-at-every-level

* this allows the strategy described in https://github.com/randy3k/AutomaticPackageReloader/issues/18 to work (otherwise not clear how `fileToMod` could work without ugly hacks): for eg:
```py
assert(fileToMod("/pathto/NimLime/core/commands/nimcheck.py")  == "NimLime.core.commands.nimcheck")
# without top-level __init__.py it'd return: "core.commands.nimcheck"
```

/cc @randy3k I'm seeing your repo also doesn't contain top-level `__init__.py` ; am I missing something?

### CODE REVIEW

**Comment by Varriount** [comment]
@timotheecour The Sublime plugin logic works by automatically importing any python files in the plugin's directory, then scanning the imported modules for certain subclasses and functions. You can look at the `Default` plugin folder (which contains the default commands) to see how this works.

This is why the new NimLime.py file contains `from NimLime.core.commands import *`

**Comment by Varriount** [comment]
To add: It appears that what is broken with regards to reloading are the event handlers (so checking on save doesn't work after reloading a NimLime). I don't know why this is occurring - I suspect it might have to do with how Sublime Text finds and stores event handler objects.

**Comment by Varriount** [comment]
More updates: It appears that this is because reloading is only calling the plugin_loaded function on the root NimLime module.

**Comment by timotheecour** [comment]
I still would like the option of having a simple way to reload the module currently being edited ; I wrote a trivial plugin to do that based on `fileToMod` (see my implementation in https://github.com/randy3k/AutomaticPackageReloader/issues/18) ; if `__init__.py` isn't typically found at top-level of a sublime plugin, I suppose I could rewrite `fileToMod` to work with that, eg:

walk up the directory until hitting the sublimetext Package dir (taking care of symlinks along the way)

**Comment by timotheecour** [comment]
closing as I've now implemented `fileToMod` based on the idea here https://github.com/Varriount/NimLime/pull/121#issuecomment-436159603 which doesn't require top-level `__init__.py` (it keeps going up until we find a subdirectory of `sublime.packages_path()`, taking care of symlinks

**Pull request closed without merging**
