### PR TITLE
Fix #26 - Unicode issues with highlighter

### LINKED ISSUE #26: Identifiers are not highlighted correctly when containing Unicode glyphs
Well, the title sums it up.

```nim
proc hash‒ignore‒style*(x: string): THash =    # proc ident is wacked when Unicodes used
  var h: THash = 0
  var i = 0
  let x‒len = x.len     # len is highlighted when there's a Unicode before in the ident
  while i < x‒len:
    var c = x[i]
    if is‒middot‒rune(cstring(x), i):    # proc ident is wacked when Unicodes used
      inc(i, 2)
  # ...
```
(The dash in the example is ofc. the Unicode...)

### PR DESCRIPTION
**Pull request by ozra**
It's not pretty, but that's regexpes for you! It seems to work out fin now when I try it in sublime.

### CODE REVIEW

**Comment by ozra** [comment]
The matchers are simply extended so they match \w and all unicodes up to the highest code point - per Nim spec.

**Comment by Varriount** [comment]
Sorry, for the delay, I haven't had the chance to actually get on my own computer until now.

**Comment by ozra** [comment]
@Varriount - that is a pretty good thing for us coders sometimes :) We've been a bit giddy only to be able to discuss https://github.com/Araq/Nim/issues/2811 with a clear view.

**Comment by ozra** [comment]
Any way of speeding up github linguist incorporation?

**Comment by Varriount** [comment]
@ozra I don't actually handle that. This repository is for just the Sublime Text plugin.

**Pull request merged**
